# Regular Numpy Arrays

In [4]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
#Covert this into a numpy array and store it as np_height_cm
import numpy as np
np_height_cm = np.array(baseball)
print(np_height_cm)

[180 215 210 210 188 176 209 200]


In [5]:
#np_height_cm is the height in cm. Convert to inches and store as np_height_in by dividing by 2.54. 
#Convert to m and store as np_height_m.
np_height_in = np_height_cm / 2.54
np_height_m = np_height_cm / 100
print(np_height_in)
print(np_height_m)

[70.86614173 84.64566929 82.67716535 82.67716535 74.01574803 69.29133858
 82.28346457 78.74015748]
[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


In [6]:
weight_lb = [140, 141, 142, 143, 144, 145, 146, 147]
#First, convert this into a numpy array and store as np_weight_lb. 
#hen convert to kg and store as np_weight_kg by dividing by 2.2
import numpy as np
np_weight_kg = np.array(weight_lb) / 2.2
print(np_weight_kg)
#Then calculate bmi by bmi = np_weight_kg / np_height_m ** 2 and print it.
bmi = np_weight_kg / np_height_m ** 2
print(bmi)

[63.63636364 64.09090909 64.54545455 65.         65.45454545 65.90909091
 66.36363636 66.81818182]
[19.64085297 13.86498845 14.63615749 14.73922902 18.51928063 21.27746995
 15.19279237 16.70454545]


In [7]:
#filter bmi values which are less than 16
light = bmi < 16
print(bmi[light])

[13.86498845 14.63615749 14.73922902 15.19279237]


In [8]:
#True = 1 and False = 0. Using this, add 2 numpy arrays to creat [4 5 2]
print(np.array([True, 5, 2]) + np.array([3, False, False]))

[4 5 2]


# 2D Numpy Arrays

In [9]:
baseball = [[180, 78.4, 25],
            [215, 102.7, 26],
            [210, 98.5, 28],
            [188, 75.2, 29]]

#Make a 2D numpy array np_baseball and print the type and shape of it. 
import numpy as np
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball.shape)



<class 'numpy.ndarray'>
(4, 3)


In [10]:
#Using the same np_baseball array, print the entire third row.
import numpy as np
print(np_baseball[2,:])
#Print the entire second column
print(np_baseball[:,1])
#Print the name of the 4th player.
print(np_baseball[3,2])

[210.   98.5  28. ]
[ 78.4 102.7  98.5  75.2]
29.0


In [11]:
conversion = np.array([1/2.54, 2.2, 1])
print(np_baseball * conversion)

[[ 70.86614173 172.48        25.        ]
 [ 84.64566929 225.94        26.        ]
 [ 82.67716535 216.7         28.        ]
 [ 74.01574803 165.44        29.        ]]


# Average, Median, and what not

In [12]:
#Make a new numpy array of just the height column. Then print the mean of the values.
import numpy as np
print(np.mean(np_baseball[:,0]))

#Print the median of the values in the second row.
print(np.median(np_baseball[1,:]))

#Print the standard deviation of the weight
print(np.std(np_baseball[:,1]))

#print the correlation between the height and the weight
print(np.corrcoef(np_baseball[:,0], np_baseball[:,1]))

198.25
102.7
12.045538593188764
[[1.         0.95865738]
 [0.95865738 1.        ]]
